name: SLSA Build

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        env:
          GO_VERSION: "1.24" # Explicitly set GO_VERSION
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt install -y libgpgme-dev libsqlite3-dev

      - name: Build binary
        run: |
          go build -o image-analyzer-go main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-analyzer-go
          path: image-analyzer-go

      - name: Upload binary to GitHub Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./image-analyzer-go
          asset_name: image-analyzer-go
          asset_content_type: application/octet-stream
