name: SLSA Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          sudo apt install -y libgpgme-dev libsqlite3-dev

      - name: Build binary
        run: |
          go build -o image-analyzer-go main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-analyzer-go
          path: image-analyzer-go

  provenance:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-analyzer-go

      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.1.0
        with:
          base64-subjects: image-analyzer-go

      - name: Upload provenance
        uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: provenance.jsonl
